#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub enum Types {
    Any,
    Nil,
    Bool,
    I64,
    F64,
    C64,
    Str,
    Regex,
    Datetime,
    Duration,
    Keyword,
    Symbol,
    List(Box<Types>),
    Vector(Box<Types>),
    Map(Box<Types>, Box<Types>),
    Set(Box<Types>),
    Array(Box<Types>, usize),
    Slice,
    Function,
    Macro,
    Struct,
    Enum,
    TypeParam,
    TypeAlias,
}
